### ISSUE TITLE
Issue template annoyance

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#1014]
We broke out the issue templates into Magic Leap and non-Magic Leap issue tiers but I don’t think this has helped clarify issues.

@chrisplatorres Are you ok with reducing the number of issue templates to one that covers all of the platform cases?

**Comment by chrisplatorres** [comment]
Yes I agree, I will PR that today.

**Comment by chrisplatorres** [comment]
Closed by #1016 .

**Comment by modulesio** [comment]
This was not resolved, since we still see a click-through template chooser (with one choice).

![Capture 25](https://user-images.githubusercontent.com/6926057/57202937-2f7da480-6f79-11e9-8338-3b97be370747.PNG)

**Comment by modulesio** [comment]
Fixed with https://github.com/exokitxr/exokit/commit/eb291ad39f6d0fc8c99cfa767796b5de1fa07a59
