### ISSUE TITLE
Update windows code signing certificate

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#1035]
Our windows (DigiCert) signing certificate is due to expire next week, so we'll need to renew for the installer flow to continue working.

**Comment by chrisplatorres** [comment]
Also the current publisher listed in cert is: "Zeo Incorporated" 

![zeoincwindows](https://user-images.githubusercontent.com/29695350/57412829-c20b8700-71b7-11e9-8fef-8e4293c48dd3.PNG)

**Comment by modulesio** [comment]
Yeah, we'd change that as part of this.

**Comment by modulesio** [comment]
Put in for this one.
