### ISSUE TITLE
localStorage process.pid reference

### ISSUE THREAD

**Issue by ngokevin** [exokitxr/exokit#1042]
**Describe the bug**
 
Error on localStorage on Android:

```
05-09 16:10:56.826 28131 28148 E exokit  : TypeError: Cannot read property 'pid' of undefined 05-09 16:10:56.826 28131 28148 E exokit  :     at getTmpname (/package/node_modules/write-file-atomic/index.js:15:28)
05-09 16:10:56.826 28131 28148 E exokit  :     at writeFileSync (/package/node_modules/write-file-atomic/index.js:94:17)
05-09 16:10:56.827 28131 28148 E exokit  :     at LocalStorage.setItem (/package/node_modules/node-localstorage/LocalStorage.js:188:7)
```

`file-atomic` refers to `process`, which is undefined, trying to get the PID to hash something.

**To Reproduce**

Steps or commands ran to reproduce the behavior:

1. `localStorage.setItem('foo', 'bar')`

**System information:**
 - OS: Android
 
 - `user-parallel`

 - Is your Exokit downloaded or built?

Built.

**Comment by modulesio** [comment]
We do have process as a global, but it is explicitly removed from window scope. Will try to think if the best way to make it visible to the local storage module stack.

**Comment by modulesio** [comment]
`write-file-atomic` code on Github: https://github.com/npm/write-file-atomic/blob/e5c9adbacea6ea722c50b6283b8e1948428ae6a8/index.js#L31

I think this is probably a generic problem, not only on Android -- all platforms should be going through this code path. Changing title accordingly.
