### ISSUE TITLE
React not setting certain values on exokit DOM

### ISSUE THREAD

**Issue by shawwn** [exokitxr/exokit#1068]
**To Reproduce**
Steps or commands ran to reproduce the behavior:
1. In Chrome, go to https://raw.githack.com/shawwn/myparcel/ddc7807847685ae4f8a128e408babc8c6917dd67/dist/index.html
2. notice the button's value increments every second, and that the button hides / unhides itself every 5 seconds.
3. Navigate to that URL in exokit CLI
4. write `console.log(document)` and observe that the button's contents are always a multiple of 10

**Additional context**
The button's contents update only when the button is unmounted and then remounted. The button is hidden / unhidden every 5 seconds, which is why the value is a multiple of 10.

**System information:**
 - OS: macOS
 
 - Exokit Version [e.g. v0.0.525]
 
 - Node version v11.13.0
 
 - Is your Exokit downloaded or built?

built

**Screenshots**

Notice `btn1.props.count` is `112` but the button is incorrectly displaying `110`:

![image](https://user-images.githubusercontent.com/59632/57972332-6f239380-795e-11e9-95a6-968ec9fc3bd3.png)

**Comment by modulesio** [comment]
The use code for this:

https://github.com/shawwn/myparcel/blob/ddc7807847685ae4f8a128e408babc8c6917dd67/src/index.js

**Comment by modulesio** [comment]
My guess is that some timer is not being fired -- if the render is not flushed, that means something did not tick on the way to the actual DOM.

Do you know which "next tick" style React is using here currently?
