### ISSUE TITLE
A-Frame scene missing elements or doesn't load

### ISSUE THREAD

**Issue by kfarr** [exokitxr/exokit#1160]
**Describe the bug**
What happened, and what did you expect to happen?

A-Frame scene that loads on Chrome ("normal") and FF (in webvr) is missing elements or doesn't load at all when loaded via exokit.
 
**To Reproduce**
Steps or commands ran to reproduce the behavior:

1. Go to this url:
https://kfarr.github.io/aframe-bus/test-bus-wasd.html

works as expected in chrome (not vr), firefox (webvr 1.1 mode with steamvr) 
![chrome-ff-Screenshot (44)](https://user-images.githubusercontent.com/470477/58757508-5a98dc80-84c2-11e9-8c9b-b594e8a99bb6.png)

see screenshot and note the green background from the a-frame "environment" component and the bus constructed using the "template" component

does not work as expected in exokit
![exokit-Screenshot (45)](https://user-images.githubusercontent.com/470477/58757512-697f8f00-84c2-11e9-8dcb-33835bcc9769.png)

if I remove the environment component, the scene renders:
https://kfarr.github.io/aframe-bus/test-bus-wasd-no-env.html
![exokit-no-env-Screenshot (46)](https://user-images.githubusercontent.com/470477/58757515-6edcd980-84c2-11e9-8413-aa6bfb402913.png)

however, the bus is still missing (template component doesn't work as expected)

**Additional context**

aframe 0.9.2

**System information:**
 - OS: [e.g. Windows 10]
 Version	10.0.17134 Build 17134

 - Exokit Version [e.g. v0.0.512]
 exokit 0.0.525

 - Node version

 
 - Npm version/build log if applicable
 
 - Is your Exokit downloaded or built?

**Screenshots**

**Comment by modulesio** [comment]
Thanks, looks like a legitimate `window` messaging issue, possibly in the timing of the VR entry.

**Comment by modulesio** [comment]
> Is your Exokit downloaded or built?

@kfarr to clarify, was this running a GitHub downloaded release (`0.0.525`)? Alternatively, could you provide the failing git hash if it's custom built?

**Comment by kfarr** [comment]
It was built from git repo around the date of issue posting, but I won't
have access to machine until Friday late to confirm exact hash.

**Comment by kfarr** [comment]
The exokit repo hash for the original ticket was: 3a5c85be5b3924956e3cce84263336dab22a7c7e

Just updated to: f01d0854ddfd0891d07df3aeef93636760b9d909

The environment component now loads as expected and I no longer see `window` errors on the console, but the bus object using the `template` component [1] does not load.
![Screenshot (48)](https://user-images.githubusercontent.com/470477/59139717-cb6c4880-8949-11e9-9b99-39be029fc62c.png)


Tonight I can make a simpler test scene that only uses the template component to better isolate the error. Meanwhile for my application I can workaround by not using that component.

[1] https://github.com/supermedium/superframe/tree/master/components/template

**Comment by kfarr** [comment]
I created an isolated test scene for the template component: https://aframe-template-component-test.glitch.me/

The console output shows a javascript error related to using template variables:
![Screenshot (50)](https://user-images.githubusercontent.com/470477/59154060-e2309f00-8a1e-11e9-821e-c36b7d287815.png)

**Comment by modulesio** [comment]
Thanks for the follow up! This should be sufficient for us to debug the template implementation.

**Comment by kfarr** [comment]
I also made a test version without template variables and unfortunately I don't see any error message in console:
https://aframe-template-component-test.glitch.me/novars.html

![Screenshot (52)](https://user-images.githubusercontent.com/470477/59154119-bf52ba80-8a1f-11e9-9064-2a96a192fab9.png)

**Comment by modulesio** [comment]
The bus template is loading fine for me with those two PR's.

**Comment by kfarr** [comment]
Awesome confirmed works!
https://github.com/kfarr/aframe-bus/commit/c732fee921347e89cc178fa3055a36569f539b03
