### ISSUE TITLE
Add flag to run script before window load

### ISSUE THREAD

**Issue by RangerMauve** [exokitxr/exokit#1166]
It'd be nice to be able to intercept the creation of new JS contexts in exokit globally.

The motivating use case for this is to be able to add guards on top of the Iframe element for custom rules on whether parent frames can access child frames' JS contexts or pointer events.

Instead of building a bunch of extra access controls, it'd be useful to handle these concerns at the level of applications being built on top of exokit.

The most flexible way to get full control over JS contexts, is to run a node module just before user content.

Ideally there should be a command line flag like `--onbeforeload` or something which specifies the path to a script to load relative to the path. Just after the global context has [loaded](https://github.com/exokitxr/exokit/blob/master/src/WindowBase.js#L378), this argument should be detected, resolved relative to the current working directory, and required.

**Comment by modulesio** [comment]
I think this is a reasonable feature request for embedders.
