### ISSUE TITLE
Downloaded Exokit.app broken on macOS 10.14.5

### ISSUE THREAD

**Issue by alex-dixon** [exokitxr/exokit#1176]
**Describe the bug**
What happened, and what did you expect to happen?
 Unable to run Exokit on macOS 10.14.5
 
**To Reproduce**
Steps or commands ran to reproduce the behavior:
1. Download Exokit from Github README
2. Open .dmg
3. Allow open from unidentified developer
4. Open app, observe nothing happens
5. From installed location in terminal got this error:
```bash
open Exokit.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Exokit.app.
```

**System information:**
 - OS: macOS 10.14.5
 
 - Exokit Version 0.0.525
 
 - Node version 12.4.0
 
 - Npm version/build log if applicable
 
 - Is your Exokit downloaded or built?
Downloaded

**Comment by todrobbins** [comment]
I am running into the same error.

**System information:**
- OS: macOS 10.14.5
- Exokit Version: 0.0.525
- Node Version: 12.2.0
- Downloaded dmg

**Comment by modulesio** [comment]
https://github.com/exokitxr/exokit/pull/1180 should fix macOS rendering.

We're currently in the process of moving the build process -- the releases hosted on GitHub are not supported and the documentation is out of date. However, building from source should work.

**Comment by todrobbins** [comment]
Thanks @modulesio!
