### ISSUE TITLE
A-Frame cursor does not track camera

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#1178]
```
node . -x webvr -t https://cursor-tests.glitch.me/
```

This site works fine in fake vr display mode (`-t`), but the camera Object3D does not track the headset as it should on Oculus Rift.

(Reported by @paperkettle)

**Comment by paperkettle** [comment]
> I noticed things parented to aframe's camera werent moving in exokit when moving my head. theyre just stuck in the scene..
> (iirc this is only when vr is entered.. the first frame that exokit flashes before entering vr appears to show attached objects transformed according to head correctly)
> then realized the camera's object3d was showing 0s for x, y, and z... 
> this is despite the fact that the camera does visually translate in the scene (in the headset, as you move your head you move through the scene)

**Comment by modulesio** [comment]
A-Frame [defers legacy WebVR](https://github.com/aframevr/aframe/blob/60ecbb358a34ff14c2d725a7674c2d2269dcc015/src/components/look-controls.js#L209) `a-camera` pose tracking to THREE.js.

The bug is that Exokit is not updating the legacy WebVR pose property for the Oculus Desktop ingest case.
