### ISSUE TITLE
A-Frame non-standard texture rendering behavior compared to Chrome / FF

### ISSUE THREAD

**Issue by kfarr** [exokitxr/exokit#1186]
**Describe the bug**
I have a simple A-Frame scene using `a-plane` entities with a transparent png texture to create a rudimentary 3D gaming object.

In Chrome and FF, the planes render as expected to display a bus and shadow. However, in Exokit there are unexpected textures displaying, such as the side of the bus rendering on the shadow, or additional wheels showing up.
 
**To Reproduce**
Steps or commands ran to reproduce the behavior:
1. Go to https://kfarr.github.io/aframe-bus/test-bus-wasd-texture-issue.html on chrome (non-webvr)
2. See screenshot [A] showing bus rendering as expected (after adjusting camera position by zooming in using scroll wheel)
3. Go to https://kfarr.github.io/aframe-bus/test-bus-wasd-texture-issue.html on exokit in webvr mode using `node . -x webvr https://kfarr.github.io/aframe-bus/test-bus-wasd-texture-issue.html`
4. See the incorrect textures in screenshot [B]

**Additional context**

**System information:**
 - OS: Windows 10
 
 - Exokit Version [e.g. v0.0.512]
exokit master branch hash: f01d0854ddfd0891d07df3aeef93636760b9d909
 
 - Node version
 v11.13.0

 - Npm version/build log if applicable
 
 - Is your Exokit downloaded or built?
built

**Screenshots**

[A] screenshot working as expected in chrome
![Screenshot (55)](https://user-images.githubusercontent.com/470477/59154347-7bfb4a80-8a25-11e9-982f-eac10b1bc8e9.png)

[B] screenshot not working as expected with red markup
![Screenshot (53)_LI](https://user-images.githubusercontent.com/470477/59154360-d09ec580-8a25-11e9-8735-3c1c3f9a884b.jpg)

**Comment by modulesio** [comment]
I wonder if this has to do with a texture stride or flip during upload 🤔.

> additional wheels showing up

That made my day, thanks. 😄

**Comment by modulesio** [comment]
Will need to reduce this one to just the bus.

**Comment by modulesio** [comment]
Current hypothesis is that this is a texture resize issue. THREE.js resizes textures by drawing to a side 2D canvas. If that is not properly cleared, you would expect artifacts like this.

```
THREE.WebGLRenderer: Texture has been resized from (1024x1280) to (1024x1024).
THREE.WebGLRenderer: Texture has been resized from (2560x2560) to (2048x2048).
THREE.WebGLRenderer: Texture has been resized from (767x186) to (512x128).
THREE.WebGLRenderer: Texture has been resized from (815x240) to (512x128).
THREE.WebGLRenderer: Texture has been resized from (725x151) to (512x128).
THREE.WebGLRenderer: Texture has been resized from (767x186) to (512x128).
THREE.WebGLRenderer: Texture has been resized from (162x168) to (128x128).
THREE.WebGLRenderer: Texture has been resized from (280x280) to (256x256).
```

**Comment by modulesio** [comment]
I think clearing the canvas2d when requesting a context (`getContext('2d')` fixes it. Exokit currently [reuses the context](https://github.com/exokitxr/exokit/blob/8733938323179d85b782f2a86721f0299e8ca863/src/DOM.js#L2342) rather than making a new one.

**Comment by kfarr** [comment]
confirmed fix!
