### ISSUE TITLE
Running an Express server

### ISSUE THREAD

**Issue by bknill** [exokitxr/exokit#1188]
Hi, 

Just about to start using this, have been running an WebVR app in cordova with a Node JS backend server for proxying files and handling the database. 

Is it possible to run an Express server within Exokit? 

I can't find any documentation around this kind of functionality.

**Comment by modulesio** [comment]
> Is it possible to run an Express server within Exokit?

You probably can add that functionality to [the `window` context](https://github.com/exokitxr/exokit/blob/362b0bf33741e7cbfa2dda5dc5ca4c0d5f47363c/src/Window.js), but it's not a default feature of Exokit.

**Comment by bknill** [comment]
Great thanks. Will give it a go.

**Comment by modulesio** [comment]
Closing this issue as answered.
