### ISSUE TITLE
A-Frame not displaying transparent textures as expected

### ISSUE THREAD

**Issue by kfarr** [exokitxr/exokit#1198]
**Describe the bug**
What happened, and what did you expect to happen?

I expected arrows from a png with alpha layer to render transparently (only showin the arrow)

![Screenshot (58)](https://user-images.githubusercontent.com/470477/59332711-b6761900-8cab-11e9-8c21-f8ac24324698.png)

 
**To Reproduce**
Steps or commands ran to reproduce the behavior:
1. Using Exokit, Go to https://aframe-building-ui.glitch.me/
`node . -x webvr https://aframe-building-ui.glitch.me/`
2. Click on "Weather"
3. See arrows rendered as black boxes (error)
4. Go to same page in chrome (non webvr) and see arrows rendering correctly

**Additional context**

**System information:**
 - OS: [e.g. Windows 10]
 
 - Exokit Version [e.g. v0.0.512]
 8733938323179d85b782f2a86721f0299e8ca863

 - Node version
 
 - Npm version/build log if applicable
 
 - Is your Exokit downloaded or built?

**Screenshots**

**Comment by modulesio** [comment]
This looks like a `400` url resolution problem rather than a transparency problem:

```
ErrorEvent {
  type: 'error',
  target: <img src="https://cors-anywhere.herokuapp.com/https://openweathermap.org/img/w/02d.png"/>,
  bubbles: false,
  cancelable: false,
  defaultPrevented: false,
  propagationStopped: false,
  currentTarget: <img src="https://cors-anywhere.herokuapp.com/https://openweathermap.org/img/w/02d.png"/>,
  message: 'img src got invalid status code (url: ' +
    '"https://cors-anywhere.herokuapp.com/https://openweathermap.org/img/w/02d.png", ' +
    'code: 400)',
  stack: 'Error: img src got invalid status code (url: ' +
    '"https://cors-anywhere.herokuapp.com/https://openweathermap.org/img/w/02d.png", ' +
    'code: 400)\n    at ' +
    'C:\\Users\\avaer\\Documents\\GitHub\\exokit2\\src\\DOM.js:2616:41\n    at ' +
    'processTicksAndRejections (internal/process/task_queues.js:89:5)'
```

**Comment by modulesio** [comment]
Looks like the error is due to missing `Origin` header that the server considers required:

```
$ curl -i https://cors-anywhere.herokuapp.com/https://openweathermap.org/img/w/02d.png
HTTP/1.1 400 Header required
Server: Cowboy
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: access-control-allow-origin
Date: Wed, 12 Jun 2019 18:14:03 GMT
Transfer-Encoding: chunked
Via: 1.1 vegur

Missing required request header. Must specify one of: origin,x-requested-with
```

**Comment by kfarr** [comment]
I attempted to validate this but in doing so I encountered another error, in the latest Exokit (23f898c2a2df9de7473a55deb78a691542b0eddc) the controllers don't appear at all, so I can't navigate to the menu where the original issue occurred.

I'll create a new ticket for this, I'm guessing it's related to another issue not this CORS stuff.

The controllers still function as expected in 8733938323179d85b782f2a86721f0299e8ca863 (the sha of revision first used in this ticket)

**Comment by kfarr** [comment]
https://github.com/exokitxr/exokit/issues/1212

**Comment by kfarr** [comment]
FYI this can also be resolved at the application level by using `crossorigin` attribute on `image` elements within `<a-assets>`

**Comment by kfarr** [comment]
FWIW Tested on originally filed issue exokit sha 8733938323179d85b782f2a86721f0299e8ca863 and using `crossorigin` component this fixes the issue as another workaround

![Screenshot (65)](https://user-images.githubusercontent.com/470477/59492087-0afcce00-8e3d-11e9-8e6b-3751a6f9ab21.png)

**Comment by modulesio** [comment]
The `fetch` part of the `400` emit from CORS anywhere should also be handled by https://github.com/exokitxr/exokit/commit/57832aa37a672065453e1f2cbcb26868baf697f0.

**Comment by kfarr** [comment]
confirmed working as expected in 57832aa37a672065453e1f2cbcb26868baf697f0 (now it loads dynamic graphics from cors anywhere)

![Screenshot (66)](https://user-images.githubusercontent.com/470477/59492830-a3e01900-8e3e-11e9-9d65-9dbdbb890a38.png)

**Comment by modulesio** [comment]
Thanks!
