### ISSUE TITLE
OSX CI: unidentified developer

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#120]
This might be a regression.

![capture 2](https://user-images.githubusercontent.com/6926057/41263271-d6c882dc-6db3-11e8-8fd1-6a025d14d885.PNG)

**Comment by chrisplatorres** [comment]
Got the same error while installing latest from `get.exokit.org` on macOS High Sierra v10.13.1:

![osxcertAnnotation 2019-04-16 184820](https://user-images.githubusercontent.com/29695350/56251290-a0b3f100-6078-11e9-9377-a5a505e01dfa.png)

**Comment by modulesio** [comment]
We probably need to go through the regular MacOS store pipeline: https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG18

**Comment by chrisplatorres** [comment]
Fixed by #962
