### ISSUE TITLE
Node 12.3.0 error "fatal error: util-inl.h: No such file or directory"

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#1201]
Got this error on Ubuntu 18.04 attempting to build Exokit on node v`12.3.0`

```
/home/chris/.node-gyp/12.3.0/include/node/node.h:107:12: fatal error: util-inl.h: No such file or directory
 #  include <util-inl.h>
            ^~~~~~~~~~~~
```

this error was fixed by commenting out line 107 below:
```
102 #if defined(NODE_WANT_INTERNALS) && NODE_WANT_INTERNALS
103 // Internally, do not include util-inl.h into files unless they need it's
104 // inline definitions.
105 #else
106 // Externally, it must be included for backwards API compatibility.
107 #  include <util-inl.h>
108 #endif
```

**Comment by chrisplatorres** [comment]
Able to repro this on windows with node 12.3.0 as well.

This does not occur with node `12.4.0`.

**Comment by modulesio** [comment]
https://github.com/nodejs/node/issues/27810

**Comment by modulesio** [comment]
I think per https://github.com/nodejs/node/issues/27810 this is a bug in Node, and not related to Exokit.

Closing accordingly.
