### ISSUE TITLE
[Linux] GLFW 3.3 not compatible

### ISSUE THREAD

**Issue by bknill** [exokitxr/exokit#1203]
Node v12.2.0, Ubuntu 18.04

After getting a successful build, I can't get the app to run.

I get nothing opening, and no errors.

Here is a trace from running the basic example. 

owner@owner-Aspire-VN7-791:~/workspace/exokit/exokit$ node --inspect . https://aframe.io/a-painter/
Debugger listening on ws://127.0.0.1:9229/fd8d821d-8ba9-47c5-8bb3-01c4b1e11ad9
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

**Comment by modulesio** [comment]
Why is the inspector being run here?

**Comment by modulesio** [comment]
Also, what is the VR configuration on this machine? Is there a VR device plugged in?

**Comment by chrisplatorres** [comment]
Able to repro on ubuntu 18.04 without any inspector ran and on multiple node versions without any VR devices plugged in.

**Comment by modulesio** [comment]
☝️ Commit for that was `9939ded`.

**Comment by chrisplatorres** [comment]
https://github.com/exokitxr/exokit/issues/1203#issuecomment-501611154
was saying that it I reproduced it on master,

but later `9939ded` was a commit that tested with no regression for this specific issue. Trying a closer commit to find exactly where the regression is from.

**Comment by chrisplatorres** [comment]
This does not occur with the previous native-graphics-deps version `.20` (pre glfw 3.3) on ubuntu.

**Comment by modulesio** [comment]
Thanks Chris, renamed the issue accordingly.

**Comment by modulesio** [comment]
From my testing, the child window hangs -- there is not even any WebGL context creation happening.

**Comment by modulesio** [comment]
I managed to fix this by moving the main event loop polling to a similar model to MacOS.

**Comment by bknill** [comment]
Great thanks guys love yer work!
