### ISSUE TITLE
Vive controllers don't appear in A-Frame menu test project

### ISSUE THREAD

**Issue by kfarr** [exokitxr/exokit#1212]
**Describe the bug**
I expect to see controllers in an a-frame project that appear in very recent versions of Exokit and also FF / Chrome.

 
**To Reproduce**
Steps or commands ran to reproduce the behavior:
1. Checkout exokit latest 23f898c2a2df9de7473a55deb78a691542b0eddc
2. Using HTC Vive and SteamVR, run `node . -x webvr https://aframe-building-ui.glitch.me/`
3. See that controllers not visible
4. Checkout exokit 8733938323179d85b782f2a86721f0299e8ca863
5. Using HTC Vive and SteamVR, run `node . -x webvr https://aframe-building-ui.glitch.me/`
6. See that controllers are visible

**Additional context**
In console I see error
> TypeError: Cannot read property 'customElements' of undefined

**System information:**
 - OS: [e.g. Windows 10]
 
 - Exokit Version [e.g. v0.0.512]
 Error on 23f898c2a2df9de7473a55deb78a691542b0eddc
 - Node version
 
 - Npm version/build log if applicable
 
 - Is your Exokit downloaded or built?

**Screenshots**
(Screenshot not helpful it just shows the same thing without controllers)

**Comment by kfarr** [comment]
I migrated this menu to another project (removed some of the dynamic weather and environment parts) Now the controller works as expected with the menu rendering.

Working using 23f898c2a2df9de7473a55deb78a691542b0eddc on file https://kfarr.github.io/aframe-bus/test-bus-wasd-23f898c.html

**Comment by modulesio** [comment]
The `customElements` Error should be fixed with https://github.com/exokitxr/exokit/commit/7149b09d1d9ebb72d43f24b49190013266637e8d.

**Comment by kfarr** [comment]
vive controllers now appear as expected
![Screenshot (62)](https://user-images.githubusercontent.com/470477/59491394-7fcf0880-8e3b-11e9-9e93-010bf39a90a6.png)
