### ISSUE TITLE
Exokit cannot run networked aframe (mozilla) tracked controller example

### ISSUE THREAD

**Issue by kfarr** [exokitxr/exokit#1214]
**Describe the bug**
What happened, and what did you expect to happen?

Cloning the `https://github.com/MozillaReality/networked-aframe` repo and running locally, I can use a chrome web browser with multiple tabs to see multiple users [screenshot 1].

Running the same using flag `-x webv` in exokit results in javascript errors.
 
**To Reproduce**
Steps or commands ran to reproduce the behavior:
1. Clone `https://github.com/MozillaReality/networked-aframe`
2. `npm install`
3. `npm run`
4. use chrome or other "2d browser" to go to `http://localhost:8080/tracked-controllers.html`, press w,a,s or d briefly to change avatar location
5. open another tab in same browser to same URL and again press w,a,s or d briefly to change avatar location, then use mouse to rotate camera to see the other avatar. you should see a scene similar to [screenshot 1]
6. load exokit 57832aa37a672065453e1f2cbcb26868baf697f0 and type `node . -x webvr http://localhost:8080/tracked-controls.html`
7. Try going to the same URL in chrome or other "2d browser" and you will not see another avatar as expected as in step #5. There are also javascript errors. [screenshot 2]

**Additional context**

**System information:**
 - OS: [e.g. Windows 10]
yes
 
 - Exokit Version [e.g. v0.0.512]
 57832aa37a672065453e1f2cbcb26868baf697f0 
 - Node version
 
 - Npm version/build log if applicable
 
 - Is your Exokit downloaded or built?

**Screenshots**
[screenshot 1]
![Screenshot (68)](https://user-images.githubusercontent.com/470477/59548465-a3aa5100-8f04-11e9-8008-4fcd69a76811.png)
[screenshot 2]
![Screenshot (70)](https://user-images.githubusercontent.com/470477/59548474-c177b600-8f04-11e9-860b-0d7b28b3d2eb.png)

**Comment by modulesio** [comment]
I ran `npm run start` and it worked great with `ed349033f43b1df40f91d906a31c947f0fa9d6c5` for me on MacOS, with all 4 players in the instructions.

I see a failure to load `/build.js` in those screenshots, which makes me think the app server is not being run correctly -- which would be out of scope for Exokit.

Can you load the local `build.js` via `curl` and get something other than a `404`?

**Comment by kfarr** [comment]
You're right this is out of scope for exokit. Works as expected, and FWIW for those playing along at home here's a direct link to a repo using networked aframe with aframe 0.9.0 that is known working on exokit (i had to delete package-lock.json to get `npm install` to work)
