### ISSUE TITLE
Electron resize corner case

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#1215]
Demo when jiggling [Exokit Studio](https://github.com/exokitxr/exokit) resize:

![studio02](https://user-images.githubusercontent.com/29695350/59556931-c767a880-8f91-11e9-9395-0306668317f6.gif)

Coming from https://github.com/exokitxr/exokit/pull/1187#issuecomment-502403739

**Comment by modulesio** [comment]
@chrisplatorres Could you post instructions for a reproduction if it's happening reliably?

**Comment by chrisplatorres** [comment]
Will try again on the latest master.

**Comment by modulesio** [comment]
@chrisplatorres Did you manage to repro this?

**Comment by chrisplatorres** [comment]
Yes, it was reproducible by having studio open and clicking to a window behind studio, this leaves the studio ui visible, but exokit engine window hidden

**Comment by modulesio** [comment]
Confirmed, the repro requires a bunch of resizes queued followed by a blur to another window before they resolve.
