### ISSUE TITLE
_normalizeUrl errors when given urls like //foo.com/bar.js

### ISSUE THREAD

**Issue by shawwn** [exokitxr/exokit#1241]
**Describe the bug**
What happened, and what did you expect to happen?

When trying to use google analytics, I noticed it spit out an error related to parsing a URL. I traced it to `_normalizeUrl` being fed a url like `//foo.com/bar.js`.

This seems to fix it:

```diff
iff --git a/src/utils.js b/src/utils.js
index 27d4fe60..8e181cd8 100644
--- a/src/utils.js
+++ b/src/utils.js
@@ -29,6 +29,9 @@ function _getBaseUrl(u, currentBaseUrl = '') {
 module.exports._getBaseUrl = _getBaseUrl;
 
 function _normalizeUrl(src, baseUrl) {
+  if (/^[/][/]/.test(src)) {
+    src = new URL(baseUrl || 'http://default.com').protocol + src;
+  }
   if (!/^(?:https?|data|blob):/.test(src)) {
     return new URL(src, baseUrl).href
       .replace(/^(file:\/\/)\/([a-z]:.*)$/i, '$1$2');
``` 
 
**To Reproduce**
Steps or commands ran to reproduce the behavior:
1. Reproduce the bug given the description above
2. Notice the error stack trace points to `_normalizeUrl`

**System information:**
 - OS: MacOS
 
 - Exokit Version [e.g. v0.0.512]
 0.0.525

 - Node version
 v11.13.0

(@modulesio: trimmed out irrelevant screenshots/quotes)

**Comment by modulesio** [comment]
This is working with the current implementation. Thanks!

```
_normalizeUrl('//foo.com/bar.js', 'https://google.com');
> "https://foo.com/bar.js"
```
