### ISSUE TITLE
The README doesn't list any downsides to using exokit

### ISSUE THREAD

**Issue by shawwn** [exokitxr/exokit#1341]
![image](https://user-images.githubusercontent.com/59632/61837019-7d9f9700-ae48-11e9-9842-16ad5e85d8cf.png)

I think these "downsides" are actually marketing material rather than legit cases where a user wouldn't want to use exokit.

1. I seem to recall hearing several times that exokit is no longer a browser. Therefore "you're looking for a traditional web browser" is a non sequitur.

2. It's hard to imagine a developer not caring at all about 3D or mixed reality. Most businesses want to integrate some form of mixed reality into their products.

3. Exokit implements most legacy standards, and implements most standards pretty strictly. I'm not sure point 3 makes sense.

The README would be more persuasive if this were cut entirely.

**Comment by modulesio** [comment]
Thanks! The README is intended as informational, not persuasive marketing material.

However I'm not sure I understand the thesis of this issue. Is the issue that the tone feels like marketing, or is inaccurate?

**Comment by modulesio** [comment]
Closing due to timeout; it's still not clear what the thesis of this issue is. Feel free to re-open if that's a mistake!
