### ISSUE TITLE
Oculus Go documentation

### ISSUE THREAD

**Issue by bknill** [exokitxr/exokit#1351]
Hi, 

Has the Oculus Go app documentation beeen removed? 

I cant find it on the site or repo?

**Comment by modulesio** [comment]
Yes it has -- Exokit _does_ work on both Go and Quest (build script here: https://github.com/exokitxr/exokit/blob/master/scripts/oculusmobile/build-android.sh)

However we're not providing any support for that path until we add a frontend and resume binary releases.

**Comment by bknill** [comment]
OK thanks @modulesio.. so we want to use Exokit to create an Oculus Go app. Is it ready for this yet?

**Comment by modulesio** [comment]
Sure, you should be able to do that with that build script. The main thing that's missing is a browser frontend so the engine can be easily tested by non-developers.

But as a developer, you should be able to drop your app into `app/index.html` (and have paths relative) and the engine should compile it into a standalone app.

**Comment by bknill** [comment]
Thanks @modulesio !
