### ISSUE TITLE
Releases don't open on Android (OnePlus 7 Pro Black Screen)

### ISSUE THREAD

**Issue by jkelleyrtp** [exokitxr/exokit#1403]
Downloaded Exokit from the landing page for Android OnePlus 7 Pro - most recent OxygenOS, and it refuses to open. Would love to collect logs if I knew where to look.

**Comment by chrisplatorres** [comment]
The APK is intended to be used on android-based Oculus headsets, not Android smartphones.

**Comment by modulesio** [comment]
Right, Google VR/ARCore support is not out if the question, but not currently supported.
