### ISSUE TITLE
Remove unused dependency cross-env

### ISSUE THREAD

**Issue by jaller94** [exokitxr/exokit#1411]
https://github.com/exokitxr/exokit/blob/bff823b560e8fa576cd5f12a5c42cb515b985f11/package.json#L49

In the GitHub search it looks like cross-env is not being used:  
https://github.com/exokitxr/exokit/search?q=cross-env&unscoped_q=cross-env

**Comment by modulesio** [comment]
Thanks for the tip.

I believe we previously used this for package.json scripts entries.

**Comment by modulesio** [comment]
https://github.com/exokitxr/exokit/commit/5ef86e79b505699a3fd16f6d32b5870d6d17de87
