### ISSUE TITLE
Can document.createElement('script'); be used?

### ISSUE THREAD

**Issue by Palmer-JC** [exokitxr/exokit#1414]
Just a quick question, can script files be added in code for Exokit?  There is a project that I use which does this.  I also might wish to do this as a way to bring in things off the net, which were not included in the APK.  

The stuff is primarily data, but if I gotta write code to serialize stuff no matter what,  might as well write code to avoid writing loader code.  Strangely, this is actually much more readable to a programmer.  Uglifiable even.

**Comment by modulesio** [comment]
Yes, Exokit just follows HTML spec. It can load both local and remote files via `<script src=>`.
