### ISSUE TITLE
WebRTC support

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#218]
This is a common feature request, since a lot of things use WebRTC for presence and chat.

The problem is the main (only?) WebRTC implementation was engineered specifically for Chrome + Firefox: https://webrtc.googlesource.com/src

It is a very large library, dabbling in many media APIs from capture to GL to codecs (has its own copy of ffmpeg for example), and just building and linking it can be a challenge (it has its own build infrastructure).

There is a node binding in the works called [`node-webrtc`](https://github.com/js-platform/node-webrtc). It includes a prebuilt bin of the main WebRTC, but it's not quite ready yet -- some things like creating media streams are missing.

https://github.com/js-platform/node-webrtc/issues/220

Still, this is something we'd like to support. Perhaps the best way forward would be to help the [`node-webrtc`](https://github.com/js-platform/node-webrtc) project complete the binding so we can slap it on `window`.

**Comment by modulesio** [comment]
It might be easier than I thought, per [`node-webrtc` discussion](https://github.com/js-platform/node-webrtc/issues/396#issuecomment-404299583). That is, there is already a [capture interface](https://github.com/js-platform/node-webrtc/blob/v0.1.6/src/webrtc/fake_audio_device.h#L50).

We could plug that into our [mic read](https://github.com/webmixedreality/exokit/blob/master/deps/exokit-bindings/webaudiocontext/src/MicrophoneMediaStream.cpp#L50), and maybe hook up the output as an [AudioNode](https://github.com/webmixedreality/exokit/blob/master/deps/exokit-bindings/webaudiocontext/src/AudioNode.cpp#L43).

**Comment by ngokevin** [comment]
A fun option is ditch the mess that is WebRTC and go https://github.com/networkprotocol/netcode.io or raw UDP.

**Comment by modulesio** [comment]
Looks like https://github.com/node-webrtc/node-webrtc has evolved and is starting to support `MediaStream` APIs. Additionally, it works on `arm64`!

I still don't like WebRTC, but it's our duty as a browser emulator to support it, and if there's an easy path to it...

**Comment by modulesio** [comment]
Exokit already has WebRTC support (Data Channels), and [more APIs are coming](https://github.com/exokitxr/exokit/pull/866).
