### ISSUE TITLE
Capture setTimeout/setImmediate timings

### ISSUE THREAD

**Issue by avaer** [exokitxr/exokit#223]
`setTimeout` and `setImmediate` are currently uncontrolled in window.

Although this semi-works, it's a problem if it's ever used for animations, since it bypasses the whole renderchain timing we have set up for `requestAnimationFrame`. Additionally, unless we control these (like we do `requestAnimationFrame`, it's a corner case when destroying a window if that window has set and uncontrolled timeout.

The straightforward way to fix this is have our own timers that only call back at frame tick time, and can be approved or thrown away by the core.

**Comment by modulesio** [comment]
[`setTimeout`](https://github.com/webmixedreality/exokit/blob/b89309146d6520d0e60a6438687578bcc8cf05ac/core.js#L895)
[`tickAnimationFrame`](https://github.com/webmixedreality/exokit/blob/b89309146d6520d0e60a6438687578bcc8cf05ac/core.js#L652)
[calling `tickAnimationFrame`](https://github.com/webmixedreality/exokit/blob/b89309146d6520d0e60a6438687578bcc8cf05ac/index.js#L1149)
