### ISSUE TITLE
Multiprocess iframe

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#382]
"Loaders" are a use case for multi-process rendering where we might prefer multiple GL runloops. We want the loader to run separately from the potentially heavier process doing the load, which is prone to hitching the render.

Prior art: https://www.chromium.org/developers/design-documents/oop-iframes

It seems a natural way to do this is to make a programmatic `<iframe detached/>` or `<webview/>` that uses node `child_process.fork()` to create a stdio-streamed child that we can `postMessage` to and from.

**Comment by ngokevin** [comment]
Loaders as in loading screens?

Also, would it make sense to make Reality Tabs each its own process?

**Comment by modulesio** [comment]
Threaded iframes (reality tabs) shipped a long time ago.
