### ISSUE TITLE
Move exokit.{sh,cmd} to root

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#551]
Right now these are in `scripts/` but the expectation is the main EXE should probably be in root.

We should move the EXEs to root and patch the launcher paths to see it there.

**Comment by chrisplatorres** [comment]
Is this still a relevant change?

**Comment by modulesio** [comment]
No, replaced by the launcher. Closing per https://github.com/exokitxr/exokit/pull/552#issuecomment-487256401
