### ISSUE TITLE
Magic leap keycode mappings

### ISSUE THREAD

**Issue by vyrnix9582046173** [exokitxr/exokit#700]
There seems to be a -68 ASCII value difference from input -> output.

Keyboard: K830 logitech
Exokit MPK v0.0.505

Example:
```
input 'z' = output '6'
```
ASCII values:
```
'z' = 122
'6' = 54
122-54= 68
```
Example input from bluetooth keyboard of `abcdefghijklmnopqrstuvwxyz`:
![dwkrcgaucaa9jkx](https://user-images.githubusercontent.com/29695350/50727676-e826fa80-10e3-11e9-91a9-177e632be779.jpg)

**Comment by chrislatorres** [comment]
Looking for how keycode ( https://github.com/webmixedreality/exokit/blob/master/examples/keycode.js ) is interpreting the keys for the url mesh ( https://github.com/webmixedreality/exokit/blob/master/examples/realitytabs.html#L1282 )

**Comment by modulesio** [comment]
There are a few layers of translation here:

- MLSDK -> `window`
- reality tabs `window` to handler
- keyCode translation into character
- append character to text buffer

First step is to find out which one(s) of these are in error.

**Comment by modulesio** [comment]
I don't think this has to do with reality tabs at all; the RT example HTML page does not deal in platform keyboard bindings. Renaming accordingly.
