### ISSUE TITLE
Magic Leap enters a bad state that can only be fixed with a full reboot

### ISSUE THREAD

**Issue by brianpeiris** [exokitxr/exokit#768]
During development, and perhaps as a consequence of restarting exokit multiple times, exokit enters a bad state where it won't start a web app and fails with an MLContext error. The only way to fix this is to reboot the magic leap device entirely

```
E NoTag   : com.exokit.app: failed to create mesh handle 4
E exokit  : Error: MLContext::Present failed to create mesh handle
E exokit  :     at Function.nativeBindings.nativeMl.requestPresent (/package/src/index.js:644:34)
E exokit  :     at XRDevice.xmDisplay.onrequestpresent.layers [as onrequestpresent] (/package/src/Window.js:1251:53)
E exokit  :     at new XRWebGLLayer (/package/src/XR.js:336:22)
E exokit  :     at WebXRManager.setSession (https://cdn.jsdelivr.net/gh/webmixedreality/exokit@v0.0.514/examples/three.js:21642:25)
E exokit  :     at session.requestAnimationFrame (webpack:///./src/client/app.js?:86:17)
E exokit  :     at animationFrame.device.onrequestanimationframe.timestamp (/package/src/XR.js:123:9)
E exokit  :     at tickAnimationFrame (/package/src/Window.js:1159:15)
E exokit  :     at Immediate._renderLoop [as _onImmediate] (/package/src/index.js:1528:18)
E exokit  :     at processImmediate (timers.js:632:19)
E exokit  :     at process.topLevelDomainCallback (domain.js:120:23)
```

**Comment by modulesio** [comment]
I've seen this too; it's super annoying. This is actually a Magic Leap operating system bug.

I already reached out to them but it's moving slowly. Could you +1/comment at https://forum.magicleap.com/hc/en-us/community/posts/360037035571-Meshing-locks-in-unspecified-error-mode?page=1#community_comment_360003619872 to signal boost it?

**Comment by brianpeiris** [comment]
Ah, gotcha. Will upvote. Thanks.

**Comment by NoahSchiffman** [comment]
I was going to but I noticed I had already upvoted it.

**Comment by chrislatorres** [comment]
I got this as well this past week when testing on the Magic Leap One apk.
