### ISSUE TITLE
Building MPK "main.cpp:11:10: fatal error: 'v8.h' file not found"

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#784]
Windows 10 - Linux subsystem: Ubuntu 18.04.1 LTS
Node v10.14.2
Npm 6.4.1
Node-gyp v3.8.0

"main.cpp:11:10: fatal error: 'v8.h' file not found" was due to Node v10.14.2 instead of Node v11.6.0 as stated in BUILDING.md instructions.

**Comment by modulesio** [comment]
Might be worth warning about that during build. We actually warn during run.

**Comment by chrisplatorres** [comment]
Getting this error when building mpk for `user-parallel` on Node v11.6.0

**Comment by chrisplatorres** [comment]
Nevermind, this is due to not using `11.15` on `user-parallel` (has been upgraded from 11.6)
