### ISSUE TITLE
Canvas not resizing

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#858]
Might be due to
- example not handling resize events
- and/or resize events not emitted

---------------------------

Command ran: `exokit$ node . -h` 
then maximize window

---------------------------

System info:
Node v11.10.1
Exokit v0.0.520

---------------------------

![Screenshot from 2019-03-14 21-50-09](https://user-images.githubusercontent.com/29695350/54405030-4d2e3c00-46a3-11e9-9bb5-86dfca43f313.png)

**Comment by modulesio** [comment]
Orr the reality tabs host page might need to synchronize this down to child iframes (reality tabs) which would all need to resize if the fake at display resizes.

**Comment by chrisplatorres** [comment]
Closing as this issue is outdated.
