### ISSUE TITLE
SteamVR tracker support

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#884]
We would like to get generic Vive trackers (not wands) exposed as gamepads in `navigator.getGamepads`.

We already support the querying infrastructure needed; we just need to hook in the case of generic trackers into the render loop.

**Comment by modulesio** [comment]
The native side of this is here: https://github.com/webmixedreality/exokit/blob/328f5274400cf736ce04c250290770bdb27f18e9/deps/openvr/src/ivrsystem.cpp#L783

The JS side would be here: https://github.com/webmixedreality/exokit/blob/328f5274400cf736ce04c250290770bdb27f18e9/src/index.js#L1238

**Comment by kfarr** [comment]
This is a screenshot of how Unity handles mapping input from SteamVR API
![Screenshot (19)](https://user-images.githubusercontent.com/470477/55454451-d7780a80-5594-11e9-9ea9-3172ffbe7914.png)

In a perfect world, as an A-Frame application developer, I can target a specific tracker and mapping, for example:
`<a-entity tracked-controls="id: OpenVR Tracker Left Foot"></a-entity>`

It is up to the user to determine mapping via existing SteamVR interface, but the above helps a developer target that mapping.

Note that the A-Frame `tracked-controls` component allows for querying controllers with `idPrefix` as well as `id` to provide backwards support such that an application that has `idPrefix: OpenVR Tracker` won't break if there is a change in behavior to append to the pose role string at the end of the current controller name (id) string.
