### ISSUE TITLE
Cannot use mouse to look around in aframe sites

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#913]
Cannot use mouse to hold left click+move around to look around on desktop (non-vr) on some aframe sites. 

Sites from aframe.io that can reproduce this:
https://aframe.io/examples/showcase/hello-metaverse/
https://aframe.io/examples/showcase/gunters-of-oasis/
https://aframe.io/examples/showcase/a-blast/

**Comment by modulesio** [comment]
A simple reproduction of this is at https://aframe.glitch.me/.

**Comment by modulesio** [comment]
The cause is that the `mousemove` event `movementX`/`movementY` are reported as zero, so A-Frame rightfully thinks there is no mouse panning going on.
