### ISSUE TITLE
Kiosk mode doesn't show exokit on the list of available app

### ISSUE THREAD

**Issue by Utopiah** [exokitxr/exokit#917]
**Describe the bug**
In Lumin OS 0.95 there is a new option for kiosk mode. Most if not all applications are listed there but not exokit even though it, the latest available build as of today, is properly installed.

**To Reproduce**
Steps or commands ran to reproduce the behavior:
1. run Lumin OS
2. have exokit installed
3. navigate in the OS to the Kiosk (beta) mode
4. list available software

**System information:**
- All done via the MagicLeap one interface

**Comment by Utopiah** [comment]
Might require a version bump.

**Comment by modulesio** [comment]
We resolved this; it was an unrelated LuminOS issue where having too many apps in the kiosk list would result in the remaining apps not being shown.
