### ISSUE TITLE
2D Reality Tabs appear twice on left side of desktop window

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#928]
Windows 10
Node v11.6.0
Exokit v0.0.520

Loaded into Windows Exokit build:
`node --experimental-worker . -h`

then opened two 2D reality tab pages, which only appeared on the left side of the window. 

![Annotation 2019-04-15 202849](https://user-images.githubusercontent.com/29695350/56175700-ed86c180-5fbd-11e9-858b-6db4081cbf14.png)

**Comment by modulesio** [comment]
Thanks, looks like a texture size divide by two error. We should fix this before shipping reality tabs.

**Comment by chrisplatorres** [comment]
Seems to be fixed now in #760 `user-parallel`.

**Comment by modulesio** [comment]
Indeed, I tackled it there. Thanks for the note.
