### ISSUE TITLE
Oculus Go font loading SEGV

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#949]
Loading `<canvas>` 2D bootstraps the font system in Skia, which tries to load default system fonts. This fails on Oculus Go, resulting in a segfault:

```
0x0000007f74d46fb4 in SkFontMgr_Android::SkFontMgr_Android(SkFontMgr_Android_CustomFonts const*) () from /home/a/exokit/android/app/src/main/arm64-v8a/libnative-main.so
```

We need to make sure the requisite font location is correct/the default font loads successfully to unlock `<canvas>` 2D on Android.

**Comment by modulesio** [comment]
Found the culprit. The reason for this error is that we are literally using the magic leap build of `skia` in the android build, and that build has an OS-specific hack to load `fonts.xml` from the package instead of the operating system: https://github.com/modulesio/skia/pull/6/files

We'll need to rebuild `skia` and somehow make this hack contingent on the `ANDROID`/`LUMIN` difference. Ideally it's detected at runtime so we can continue to share the lib across both platforms...

**Comment by chrisplatorres** [comment]
That is the change from here? https://github.com/modulesio/skia/commit/534a3a034a0a81d67898ece5c3a4040e26e9a7b9

**Comment by modulesio** [comment]
Yeah, probably.

For runtime detection I think the presence of `ANDROID_HOME` might work: https://github.com/modulesio/skia/pull/6/files#diff-17ccc70e187937a2f38ca4845a74ef75R784

**Comment by chrisplatorres** [comment]
found a reference for android env variables:
```
ANDROID_ASSETS: /system/app
ANDROID_DATA: /data
ANDROID_ROOT: /system
ASEC_MOUNTPOINT: /mnt/asec
BOOTCLASSPATH: /system/framework/core.jar:/system/framework/core-...
EXTERNAL_STORAGE: /storage/sdcard
LOOP_MOUNTPOINT: /mnt/obb
PATH: /sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
```

[source](https://webcache.googleusercontent.com/search?q=cache:iqLSSxtz0zQJ:www.herongyang.com/Android/System-Information-System-Environment-Variables.html+&cd=2&hl=en&ct=clnk&gl=us&client=firefox-b-1-d)

**Comment by modulesio** [comment]
Yes but the real question is does LUMIN define these, so can we rely on it to differentiate?
