### ISSUE TITLE
Move to GLFW 3.3

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#954]
After many years of waiting, it's released! https://www.glfw.org/Version-3.3-released.html

We've had a few issues with 3.2 that were fixed in 3.3, so a spare cycle could be used to upgrade.

The dependency is in https://github.com/modulesio/node-native-canvas-deps.

**Comment by modulesio** [comment]
We need this one for transparent window support (might be needed in Studio).

**Comment by chrisplatorres** [comment]
What would transparent windows be used for?
