### ISSUE TITLE
Add debugging documentation

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#955]
Currently we recommend that `ndb` is used to debug Exokit in the documentation, but that's not commonly used. Instead most issues are related to native modules, were a native debugger is better.

We should update the documentation with a debugging guide accordingly. Even just pointers on how to bootstrap a debugging session for each platform would be useful.

**Comment by chrisplatorres** [comment]
Debugging documentation is now at: https://github.com/exokitxr/exokit/blob/master/docs/sdk/debugging.md

Does this cover this issue, or should their be details per-platform?

**Comment by modulesio** [comment]
That documentation still seems very fragmented and not tested, and isn't covering how people actually debug. For example, on Windows, you're probably using either Visual Studio or `windgb`, not MinGW.

Perhaps a better solution than documenting this is delivering a better debugging solution in the studio, as well as a remote debugger for the mobiles.

And _then_ document that functionality.

**Comment by chrisplatorres** [comment]
I agree on integrating the debugger into studio. Is this a case where there will still be a need to have a debugger doc like this for the more technical users?

**Comment by modulesio** [comment]
Let's separate the debuggers into two cases.

One is the user debugging their JS. This is probably most important, and would be expected to be used by HTML/JS code authors, including framework authors. This is a concern for the studio. The documentation extent of this would be how to use it in the studio.

The other case is internal Exokit engine debugging, which is also important for documenting but probably doesn't need to be front-facing. This seems to be where the document is currently leaning in.

This issue should be broken out into two issues in that case.

**Comment by chrisplatorres** [comment]
Ok I will close and break out the new issues.
