### ISSUE TITLE
Exokit command line flags doc needs to be updated

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#967]
The doc page for [exokit command line flags](https://github.com/exokitxr/exokit/blob/5d27283af94f23e6fe94e68bd339324401a93e84/docs/sdk/exokitCommandLineFlags.md) needs to be updated.

![cliflagsCapture](https://user-images.githubusercontent.com/29695350/56537235-a6e91800-6525-11e9-847e-d9995bbed34f.PNG)

**Comment by ChrisEddy** [comment]
can we get the updated list for the launcher plz?

**Comment by modulesio** [comment]
The list in the source is here: https://github.com/exokitxr/exokit/blob/master/src/index.js#L63

**Comment by chrisplatorres** [comment]
Also updated here https://github.com/exokitxr/exokit/blob/fabd210ffe823d125ec6274c2a926a6d5e2ef8b7/docs/sdk/exokitCommandLineFlags.md

This issue will be closed by #971

**Comment by modulesio** [comment]
Closed per #971, thanks!
