### ISSUE TITLE
Oculus Mobile Multiview rendering

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#981]
The [OVR_multiview2 extension](https://www.khronos.org/registry/OpenGL/extensions/OVR/OVR_multiview2.txt) allows for a cleaner GL call path (if the client uses it).

[THREE.js is adding support]https://github.com/mrdoob/three.js/pull/16316/files/08ded2c0b55919b02d691dd0fa3b8806123bc5f3..1e13fbdd086cc1eaf9cda0994b29d0335480ae4c) and we might as well follow suit.

This should be relatively straightforward since we already just bind directly to OpenGL.

**Comment by chrisplatorres** [comment]
Relevant link https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-multiview/

**Comment by chrisplatorres** [comment]
I built a multiview three.js here: https://chrisplatorres.github.io/three.js/build/three.js

just add it and:
```js
const renderer = new THREE.WebGLRenderer( { antialias: true, multiview: true } );
```

**Comment by chrisplatorres** [comment]
Closed by https://github.com/exokitxr/exokit/pull/1122.
